name: "test"
on: [push, pull_request, workflow_dispatch]

jobs:
  functionalSelfTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pack
        run: npm run pack

      - name: Jest tests
        run: npm run test

      - id: actionYmlAgainstGithubActions
        name: Validate action.yml against github-action schema
        uses: ./
        with:
          file: 'action.yml'
          schema: 'https://json.schemastore.org/github-action.json'

      - name: Check actionYmlAgainstGithubActions result
        if: steps.actionYmlAgainstGithubActions.outputs.errorType != ''
        run: exit 1

      - id: actionYmlAgainstAngular
        name: Validate action.yml against wrong schema
        continue-on-error: true
        uses: ./
        with:
          file: 'action.yml'
          schema: 'https://raw.githubusercontent.com/angular/angular-cli/master/packages/angular/cli/lib/config/workspace-schema.json'

      - name: Check actionYmlAgainstAngular result
        if: |
          steps.actionYmlAgainsTravis.outputs.errorType != 'validation' ||
          steps.actionYmlAgainsTravis.outcome != 'failure'
        run: exit 1

      - id: packageJsonAgainsLocalSchema
        name: Validate package.json against local schema
        continue-on-error: true
        uses: ./
        with:
          file: 'package.json'
          schema: 'tests/integration/package.schema.json'

      - name: Check packageJsonAgainsLocalSchema result
        if: steps.packageJsonAgainsLocalSchema.outputs.errorType != ''
        run: exit 1